### ISSUE TITLE
Datenangaben mit geringer Zeichenanzahl führen zu php Fehler

### ISSUE THREAD

**Issue by connine** [grusch-it/isotope_payment_sepa#1]
Test-Angaben, wie z.B. "0000", verursachen einen php Fehler

``` php
Warning: str_repeat(): Second argument has to be greater than or equal to 0 in system/modules/isotope_payment_sepa/classes/SepaPayment.php on line 124
```

EDIT: sorry - ich war zu voreilig. Fehler liegt nicht an den Datenangaben, sondern in Verbindung mit meiner Isotope Version.

**Comment by grusch-it** [comment]
Welche Version von Isotope ist im Einsatz?

**Comment by connine** [comment]
Version 2.2.5

Der Fehler tritt übrigens doch weiterhin bei Testeingaben auf, die z.B. nicht der Mindestlänge einer deutschen IBAN entsprechen.

**Comment by grusch-it** [comment]
Behoben in cb6bcd0dfed53a931f4e062dfa57b91fde9f5d01

**Comment by connine** [comment]
Fehler existiert leider weiterhin. Eingaben wie "0000" sind einfach zu kurz für die Weitere Verarbeitung in SepaPayment.php aber sie werfen natürlich keinen Fehler bei $objWidget->hasErrors(), da sie ja an sich valide in einem Texteingabefeld sind.

Hier mal die Ausgaben von $objWidget->hasErrors() vor [Zeile 142](https://github.com/grusch-it/isotope_payment_sepa/blob/cb6bcd0dfed53a931f4e062dfa57b91fde9f5d01/classes/SepaCheckoutForm.php#L142)

![sepa_error](https://cloud.githubusercontent.com/assets/10073733/9221816/614f9770-40ed-11e5-8c8c-a61a9393b18d.JPG)
