### ISSUE TITLE
Tag angaben werde mit ausgegeben.

### ISSUE THREAD

**Issue by sebssch** [grusch-it/isotope_payment_sepa#4]
##sepa_holder##
##sepa_iban_masked##
##sepa_bic##

werden in der E-Mail auch bei Verwendung anderer Zahlungsart ausgegeben.

**Comment by grusch-it** [comment]
Mit Hilfe der [SimpleTokens können auch if-Abfragen](https://isotopeecommerce.org/de/handbuch/v/2.4/r/simple-tokens.html) realisiert werden:

```
{if payment_label=="SEPA"}
##sepa_holder##
##sepa_iban_masked##
##sepa_bic##
{endif}
```

Ich hab das in der Beschreibung der Erweiterung im Contao Extension Repository entsprechend ergänzt. Danke für den Hinweis!

**Comment by sebssch** [comment]
Super vielen Dank! :)
